### PR TITLE
Try rector dev-main

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba @Wirone this is rector/rector:dev-main in my module, and it got error:

```bash
Error: ] Could not process                                                      
         "test/Database/Infrastructure/Persistence/AlbumTrackSummary/SQLAlbumTra
         ckSummaryRepositoryTest.php" file, due to:                             
         "System error: "Class 'ReflectionUnionType' not found"                 
         Run Rector with "--debug" option and post the report here:             
         https://github.com/rectorphp/rector/issues/new". On line: 12      
```

which bootstrap is too late for loaded.

**Comment by TomasVotruba** [comment]
Great, I have exactly the same issue on my PHP 7.2 project.

**Comment by samsonasik** [comment]
I tried using update using https://github.com/rectorphp/rector/commit/bcf77dc873db1a5a8699bb898836b710dd53d61c#diff-af45d2bd8e8a2557399c1da1effd016925338388c0028f7c54324501dffa1915

in diff, it seems the autoload in composer is changed:

https://github.com/rectorphp/rector/commit/bcf77dc873db1a5a8699bb898836b710dd53d61c#diff-af45d2bd8e8a2557399c1da1effd016925338388c0028f7c54324501dffa1915

**Comment by samsonasik** [comment]
Ok, [1 commit after 0.13](https://github.com/samsonasik/ci4-album/pull/11/commits/d18c5d8352d11cce2bf2d0421e8b82c345b39d94), still working.

**Comment by samsonasik** [comment]
Ok, [11 commit after 0.13](https://github.com/samsonasik/ci4-album/pull/11/commits/742760cf4b84a09a630e084e0649424f12b7bdaa), already not working.

**Comment by samsonasik** [comment]
@TomasVotruba 0.13.1 still not working https://github.com/samsonasik/ci4-album/runs/6630188966?check_suite_focus=true#step:10:28

**Comment by samsonasik** [comment]
I created issue https://github.com/rectorphp/rector/issues/7191 for it,.

**Comment by TomasVotruba** [comment]
Could you add me as a contributor? I'm trying to run this PR

**Comment by samsonasik** [comment]
@TomasVotruba I've added you as collaborator

**Pull request closed without merging**
